### ISSUE TITLE
cmake/UseDoxygen.cmake problem

### ISSUE THREAD

**Issue by egull** [aeantipov/gftools#1]
I believe we had the same issue in ALPSCore and fixed it there: CMake's UseDoxygen complains:

CMake Warning (dev) at cmake/UseDoxygen.cmake:138 (get_target_property):
  Policy CMP0045 is not set: Error on non-existent target in
  get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  get_target_property() called with non-existent target "doc".
Call Stack (most recent call first):
  CMakeLists.txt:28 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by aeantipov** [comment]
Thanks! Fixed with d0fa6ae
