### ISSUE TITLE
Example01 has bad index when run

### ISSUE THREAD

**Issue by ryanlevy** [aeantipov/gftools#3]
Using clang, the example compiles but does complete successfully

```
...
/Users/user/UMICH/software/gftools/./gftools/real_grid.hpp:155: Invoking find
/Users/user/UMICH/software/gftools/./gftools/real_grid.hpp:158: Point to find is out of bounds, 6.28319>5
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: wrong index: 6.283185
Abort trap: 6
```

The offending line is [here](https://github.com/aeantipov/gftools/blob/b7c377af167cbc34ac3c67615b1418384207bf33/example/example01.cpp#L86)
`std::cout << G1(2*PI) << std::endl;`

---

I am running OSX 10.10.5 with clang version:

```
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

**Comment by aeantipov** [comment]
Ok, better later than never. Fixed with b740a598b03876977c6c3f3215d2501bba78a486 . This required to rewrite most of the exceptions. Please check. Closing for now.
